# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 16:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hanzi_basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedSyllable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BinaryField()),
                ('file_extension', models.CharField(max_length=40)),
                ('syllable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hanzi_basics.PinyinSyllable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recordedsyllable',
            unique_together=set([('user', 'syllable')]),
        ),
    ]
