# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedsyllable',
            name='content_as_wav',
            field=models.BinaryField(null=True),
        ),
    ]
