# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0002_recordedsyllable_content_as_wav'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedsyllable',
            name='content_as_normalized_wav',
            field=models.BinaryField(null=True),
        ),
    ]
