# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0004_recordedsyllable_content_as_silence_stripped_wav'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedsyllable',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
