# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0005_recordedsyllable_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedsyllable',
            name='normalize_version',
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
    ]
