# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0006_recordedsyllable_normalize_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedsyllable',
            name='recording_ok',
            field=models.NullBooleanField(),
        ),
    ]
