# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0007_recordedsyllable_recording_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedsyllable',
            name='audio_normalized_volume',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recordedsyllable',
            name='audio_original',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recordedsyllable',
            name='audio_silence_stripped',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recordedsyllable',
            name='audio_wav',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
