# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 21:19
from __future__ import unicode_literals

from django.db import migrations
from tonerecorder.models import RecordedSyllable as RecordedSyllableModel

def dump_audio_content_to_files(apps, schema_editor):
    RecordedSyllable = Person = apps.get_model('tonerecorder', 'RecordedSyllable')
    for rs in RecordedSyllable.objects.all():
        if rs.content is not None:
            original_path = RecordedSyllableModel.create_audio_path(rs, 'original')
            with open(original_path, 'wb') as f:
                f.write(rs.content)
            rs.audio_original = original_path

        if rs.content_as_wav is not None:
            wav_path = RecordedSyllableModel.create_audio_path(rs, 'wav')
            with open(wav_path, 'wb') as f:
                f.write(rs.content_as_wav)
            rs.audio_wav = wav_path

        if rs.content_as_normalized_wav is not None:
            normalized_path = RecordedSyllableModel.create_audio_path(rs, 'volume_normalized')
            with open(normalized_path, 'wb') as f:
                f.write(rs.content_as_normalized_wav)
            rs.audio_normalized_volume = normalized_path

        if rs.content_as_silence_stripped_wav is not None:
            stripped_path = RecordedSyllableModel.create_audio_path(rs, 'silence_stripped')
            with open(stripped_path, 'wb') as f:
                f.write(rs.content_as_silence_stripped_wav)
            rs.audio_silence_stripped = stripped_path

        rs.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0008_auto_20160811_2108'),
    ]

    operations = [
        migrations.RunPython(dump_audio_content_to_files),
    ]
