# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0009_auto_20160811_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordedsyllable',
            name='content',
        ),
        migrations.RemoveField(
            model_name='recordedsyllable',
            name='content_as_normalized_wav',
        ),
        migrations.RemoveField(
            model_name='recordedsyllable',
            name='content_as_silence_stripped_wav',
        ),
        migrations.RemoveField(
            model_name='recordedsyllable',
            name='content_as_wav',
        ),
    ]
