# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0010_auto_20160811_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedsyllable',
            name='native',
            field=models.BooleanField(default=False),
        ),
    ]
