# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 17:21
from __future__ import unicode_literals

from django.db import migrations

def mark_recordings_as_native(apps, schema_editor):
    RecordedSyllable = apps.get_model('tonerecorder', 'RecordedSyllable')
    RecordedSyllable.objects.update(native=True)

class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0011_recordedsyllable_native'),
    ]

    operations = [
        migrations.RunPython(mark_recordings_as_native)
    ]
