# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0014_auto_20160928_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedsyllable',
            name='audio_mp3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
