# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0015_recordedsyllable_audio_mp3'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedsyllable',
            name='original_md5hex',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
